import type { NextPage } from 'next'

import React, { Suspense } from 'react'
import Head from 'next/head'
import tw, { styled } from 'twin.macro'

import Welcome from '@/components/Welcome.server'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Suspense fallback={<div>Loading...</div>}>
        <Welcome />
      </Suspense>
    </>
  )
}

export default Home
